// Smoke test for the `js-yaml` dependency bump (transitive: @blaxel/core ->
// @hey-api/client-fetch -> @hey-api/openapi-ts -> @hey-api/json-schema-ref-parser,
// pinned in pnpm-workspace.yaml overrides). Added here as an exact-pinned devDependency
// so the test imports the real package the lockfile resolves, not a phantom hoisted
// transitive -- js-yaml is never imported from this repo's own source, and grepping
// @blaxel/core's compiled dist confirms @hey-api/openapi-ts (and therefore js-yaml) is
// only ever referenced in a "generated by" header comment, never required at runtime.
//
// See GHSA-5p4m-2wfm-xmqj (high): fixed in js-yaml 4.3.1, which replaces an
// `objectKeys.indexOf(pairKey)` linear array scan with a hash-object lookup in
// `!!omap` duplicate-key detection (lib/type/omap.js), removing O(n^2) behaviour
// when parsing a `!!omap` sequence with many entries.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import yaml from 'js-yaml';

test('js-yaml loads a well-formed !!omap into an ordered array of pairs', () => {
  const doc = '--- !!omap\n- a: 1\n- b: 2\n- c: 3\n';
  const result = yaml.load(doc);

  assert.ok(Array.isArray(result));
  assert.deepEqual(result, [{ a: 1 }, { b: 2 }, { c: 3 }]);
});

test('js-yaml rejects a !!omap with a duplicate key', () => {
  const doc = '--- !!omap\n- a: 1\n- a: 2\n';

  assert.throws(() => yaml.load(doc));
});

test('js-yaml parses a large !!omap without quadratic blowup (GHSA-5p4m-2wfm-xmqj)', () => {
  // 150k unique keys. On the vulnerable 4.3.0 (linear-scan duplicate check) this
  // measured ~11.6s locally; on the fixed 4.3.1 (hash-lookup) it measured ~0.4s.
  // The assertion is a generous absolute timeout -- a hang detector, not a
  // performance benchmark -- picked with wide margin on both sides of that gap.
  const N = 150_000;
  const lines = ['--- !!omap'];
  for (let i = 0; i < N; i++) lines.push(`- key${i}: ${i}`);
  const doc = lines.join('\n') + '\n';

  // Minimum of 3 runs: immune to one-off scheduling noise inflating a single sample.
  let best = Infinity;
  let result;
  for (let i = 0; i < 3; i++) {
    const t0 = performance.now();
    result = yaml.load(doc);
    best = Math.min(best, performance.now() - t0);
  }

  assert.equal(result.length, N);
  assert.ok(
    best < 3000,
    `expected !!omap parse of ${N} entries to finish well under 3s (hash-lookup fix), took ${best.toFixed(1)}ms -- looks like the quadratic duplicate-key scan is back`,
  );
});
